import logging
from sqlalchemy import text
from conexiones import obtener_conexion_oracle

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def inicializar_datos_oracle():
    """
    Crea una tabla en Oracle y la puebla con datos de prueba.
    """
    motor = obtener_conexion_oracle()
    if not motor:
        return

    logging.info("Preparando datos de prueba en Oracle...")

    # El bloque 'with motor.connect()' maneja el ciclo de vida de la conexión
    with motor.connect() as conn:
        # Iniciar una transacción explícita
        with conn.begin(): 
            # 1. Intentamos crear la tabla (Ignoramos el error si ya existe)
            try:
                conn.execute(text("""
                    CREATE TABLE candidatos_ape (
                        id_candidato NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nombre VARCHAR2(100),
                        profesion VARCHAR2(100),
                        experiencia_anios NUMBER
                    )
                """))
                logging.info("Tabla 'candidatos_ape' creada en Oracle.")
            except Exception:
                logging.info("La tabla 'candidatos_ape' ya existe.")

            # Limpiamos la tabla por si ejecutamos el script varias veces
            conn.execute(text("DELETE FROM candidatos_ape"))

            # 2. Datos de prueba a insertar
            datos = [
                {"nombre": "Ana Perez", "profesion": "Desarrolladora Go", "exp": 2},
                {"nombre": "Luis Gomez", "profesion": "Analista de Datos", "exp": 5},
                {"nombre": "Maria Lopez", "profesion": "Ingeniera DevOps", "exp": 3}
            ]
            
            # 3. Query Parametrizada (nota los dos puntos: :nombre, :profesion, :exp)
            # SQLAlchemy mapea automáticamente las claves de nuestro diccionario a estos parámetros.
            query_insert = text("""
                INSERT INTO candidatos_ape (nombre, profesion, experiencia_anios) 
                VALUES (:nombre, :profesion, :exp)
            """)
            
            conn.execute(query_insert, datos)
            logging.info(f"Se insertaron {len(datos)} registros de prueba en Oracle.")